### ISSUE TITLE
LICENSE.md describes this work as proprietary

### ISSUE THREAD

**Issue by madidier** [tunnelvisionlabs/antlr4-grammar-postgresql#1]
I've seen the latest commit on this repository changed the license in the source files headers to MIT, but LICENCE.md was not changed. This looks like an oversight ; update LICENSE.md ?

**Comment by sharwell** [comment]
This repository contains different files with different licenses. While the code here in the master branch appears to be mostly MIT-licensed, there is other code in the [postgresql-parser](https://github.com/sharwell/antlr4-grammar-postgresql/tree/postgresql-parser) branch in my fork which is proprietary.

:memo: The lexer for this project was made possible under Tunnel Vision Labs' [sponsored development program](http://tunnelvisionlabs.com/SponsoredDevelopment.pdf) from a contributor who wished to remain anonymous.
